### ISSUE TITLE
Set the widget to the edge

### ISSUE THREAD

**Issue by SamBecca16** [Shiewk/widgets#1]
Cool mod, but I will like to be able to set the widgets close to the edges and being able to edit the size of the background of the text, like this: 
![imagen](https://github.com/user-attachments/assets/a36dd86d-e23f-470c-b588-bbc397cc0ff6)

**Comment by Shiewk** [comment]
I've added a few more widget settings in version 1.1.0. Just set the text alignment to left, padding to 0 and height to 9, then you can move the widget to the edges.
